// src/styles.js
export const styles = {
  container: {
    display: 'flex',
    width: '100%',
    minHeight: 'calc(100vh - 80px)',
    margin: 0,
    padding: 0,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    gap: '0',
  },
  rightColumn: {
    flex: 1,
    padding: '2.5rem',
    overflowY: 'auto',
    minHeight: 'calc(100vh - 80px)',
    background: 'transparent',
  },
  notesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(300px, 1fr))',
    gap: '1.5rem',
    alignItems: 'start',
  },
  noteCard: {
    backgroundColor: '#ffffff',
    padding: '1.75rem',
    borderRadius: '16px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
    transition: 'all 0.3s ease',
    border: '1px solid #f1f5f9',
    minHeight: '250px',
    display: 'flex',
    flexDirection: 'column',
    cursor: 'pointer',
    animation: 'fadeIn 0.4s ease',
  },
  noteTitle: {
    fontSize: '1.35rem',
    fontWeight: '700',
    color: '#1e293b',
    margin: '0 0 1rem 0',
    lineHeight: '1.4',
    letterSpacing: '-0.3px',
  },
  noteContent: {
    color: '#475569',
    lineHeight: '1.7',
    margin: '0 0 1.5rem 0',
    fontSize: '0.975rem',
    flex: 1,
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 4,
    textOverflow: 'ellipsis',
  },
  noteFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
    paddingTop: '1rem',
    borderTop: '1px solid #f1f5f9',
  },
  noteDate: {
    color: '#94a3b8',
    fontSize: '0.85rem',
    fontWeight: '500',
  },
  noteActions: {
    display: 'flex',
    gap: '0.625rem',
  },
  searchFilterContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    backdropFilter: 'blur(10px)',
    borderRadius: '16px',
    padding: '1.5rem',
    marginBottom: '2rem',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
  },
  searchBox: {
    position: 'relative',
    marginBottom: '1rem',
  },
  searchInput: {
    width: '100%',
    padding: '1rem 3rem 1rem 1.25rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    backgroundColor: '#ffffff',
    outline: 'none',
    fontFamily: 'inherit',
    color: '#1e293b',
    '::placeholder': {
      color: '#94a3b8',
    },
  },
  searchIcon: {
    position: 'absolute',
    right: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    fontSize: '1.2rem',
  },
  filterControls: {
    display: 'flex',
    gap: '1.5rem',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  filterGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  filterLabel: {
    fontSize: '0.9rem',
    fontWeight: '600',
    color: '#475569',
    whiteSpace: 'nowrap',
  },
  filterSelect: {
    padding: '0.5rem 1rem',
    border: '2px solid #e2e8f0',
    borderRadius: '8px',
    fontSize: '0.9rem',
    backgroundColor: '#ffffff',
    outline: 'none',
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  clearButton: {
    padding: '0.5rem 1rem',
    border: '2px solid #e2e8f0',
    borderRadius: '8px',
    backgroundColor: 'transparent',
    color: '#64748b',
    fontSize: '0.9rem',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    marginLeft: 'auto',
  },
  emptyState: {
    textAlign: 'center',
    padding: '4rem 2rem',
    color: '#64748b',
    background: 'rgba(255, 255, 255, 0.98)',
    backdropFilter: 'blur(10px)',
    borderRadius: '20px',
    border: '2px dashed #e2e8f0',
  },
  emptyStateIcon: {
    fontSize: '3rem',
    marginBottom: '1rem',
    opacity: 0.7,
  },
  emptyStateTitle: {
    fontSize: '1.5rem',
    fontWeight: '600',
    margin: '0 0 1rem 0',
    color: '#334155',
  },
  emptyStateText: {
    fontSize: '1rem',
    lineHeight: '1.6',
    margin: 0,
    color: '#64748b',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '1rem',
    animation: 'fadeIn 0.2s ease-out',
  },
  modalContent: {
    background: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)',
    borderRadius: '16px',
    width: '100%',
    maxWidth: '600px',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    overflow: 'hidden',
    animation: 'slideUp 0.3s ease-out',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1.5rem 1.5rem 1rem',
    borderBottom: '1px solid #e2e8f0',
    background: 'transparent',
  },
  modalTitle: {
    fontSize: '1.5rem',
    fontWeight: '700',
    margin: 0,
    color: '#1e293b',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  modalCloseButton: {
    background: 'none',
    border: 'none',
    fontSize: '2rem',
    color: '#64748b',
    cursor: 'pointer',
    padding: '0.25rem 0.75rem',
    borderRadius: '8px',
    transition: 'all 0.2s ease',
    lineHeight: 1,
    ':hover': {
      backgroundColor: '#f1f5f9',
      color: '#334155',
    },
  },
  modalBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  modalFooter: {
    padding: '1.5rem',
    borderTop: '1px solid #e2e8f0',
    background: '#f8fafc',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  modalInput: {
    padding: '1rem 1.25rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    backgroundColor: '#ffffff',
    outline: 'none',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
    color: '#1e293b',
    ':focus': {
      borderColor: '#667eea',
      boxShadow: '0 0 0 3px rgba(102, 126, 234, 0.1)',
    },
  },
  modalTextarea: {
    padding: '1rem 1.25rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    fontSize: '1rem',
    resize: 'vertical',
    transition: 'all 0.3s ease',
    backgroundColor: '#ffffff',
    outline: 'none',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
    minHeight: '200px',
    lineHeight: '1.6',
    color: '#1e293b',
    ':focus': {
      borderColor: '#667eea',
      boxShadow: '0 0 0 3px rgba(102, 126, 234, 0.1)',
    },
  },
  modalCreateButton: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    border: 'none',
    padding: '1rem 1.5rem',
    borderRadius: '12px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    width: '100%',
    ':hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 8px 20px rgba(102, 126, 234, 0.4)',
    },
    ':active': {
      transform: 'translateY(0)',
    },
  },
  modalCancelButton: {
    background: 'transparent',
    color: '#64748b',
    border: '2px solid #e2e8f0',
    padding: '0.75rem 1.5rem',
    borderRadius: '12px',
    fontSize: '0.9rem',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    width: '100%',
    ':hover': {
      backgroundColor: '#f1f5f9',
      borderColor: '#cbd5e1',
    },
  },
  modalTip: {
    color: '#64748b',
    textAlign: 'center',
    fontSize: '0.8rem',
    display: 'block',
    marginTop: '0.5rem',
  },
};

// Add CSS animations
const style = document.createElement('style');
style.textContent = `
  @keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }
  
  @keyframes slideUp {
    from { 
      opacity: 0;
      transform: translateY(20px);
    }
    to { 
      opacity: 1;
      transform: translateY(0);
    }
  }
`;
document.head.appendChild(style);