// src/styles.js
export const styles = {
  container: {
    display: 'flex',
    width: '100%',
    minHeight: 'calc(100vh - 80px)',
    margin: 0,
    padding: 0,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    gap: '0',
  },
  leftColumn: {
    width: '450px',
    minWidth: '450px',
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    backdropFilter: 'blur(10px)',
    padding: '2.5rem',
    boxShadow: '4px 0 20px rgba(0, 0, 0, 0.08)',
    height: 'calc(100vh - 80px)',
    overflow: 'hidden',
    position: 'sticky',
    top: '80px',
    left: 0,
  },
  rightColumn: {
    flex: 1,
    padding: '2.5rem',
    overflowY: 'auto',
    minHeight: 'calc(100vh - 80px)',
    background: 'transparent',
  },
  noteForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
    height: '100%',
  },
  input: {
    padding: '1rem 1.25rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
    backgroundColor: '#ffffff',
    outline: 'none',
    fontFamily: 'inherit',
  },
  textarea: {
    padding: '1rem 1.25rem',
    border: '2px solid #e2e8f0',
    borderRadius: '12px',
    fontSize: '1rem',
    resize: 'vertical',
    transition: 'all 0.3s ease',
    backgroundColor: '#ffffff',
    outline: 'none',
    fontFamily: 'inherit',
    lineHeight: '1.6',
  },
  addButton: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    border: 'none',
    padding: '1.125rem 1.5rem',
    borderRadius: '12px',
    fontSize: '1.05rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    boxShadow: '0 4px 12px rgba(102, 126, 234, 0.4)',
  },
  notesHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
    padding: '1.5rem',
    background: 'rgba(255, 255, 255, 0.98)',
    backdropFilter: 'blur(10px)',
    borderRadius: '16px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
  },
  notesTitle: {
    fontSize: '2rem',
    fontWeight: '700',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    margin: 0,
    letterSpacing: '-0.5px',
  },
  notesCount: {
    backgroundColor: '#f1f5f9',
    color: '#475569',
    padding: '0.625rem 1.25rem',
    borderRadius: '10px',
    fontSize: '0.95rem',
    fontWeight: '600',
    border: '1px solid #e2e8f0',
  },
  notesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '1.5rem',
    alignItems: 'start',
  },
  noteCard: {
    backgroundColor: '#ffffff',
    padding: '1.75rem',
    borderRadius: '16px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
    transition: 'all 0.3s ease',
    border: '1px solid #f1f5f9',
    minHeight: '250px',
    display: 'flex',
    flexDirection: 'column',
    cursor: 'pointer',
    animation: 'fadeIn 0.4s ease',
  },
  noteTitle: {
    fontSize: '1.35rem',
    fontWeight: '700',
    color: '#1e293b',
    margin: '0 0 1rem 0',
    lineHeight: '1.4',
    letterSpacing: '-0.3px',
  },
  noteContent: {
    color: '#475569',
    lineHeight: '1.7',
    margin: '0 0 1.5rem 0',
    fontSize: '0.975rem',
    flex: 1,
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 4,
    textOverflow: 'ellipsis',
  },
  noteFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
    paddingTop: '1rem',
    borderTop: '1px solid #f1f5f9',
  },
  noteDate: {
    color: '#94a3b8',
    fontSize: '0.85rem',
    fontWeight: '500',
  },
  noteActions: {
    display: 'flex',
    gap: '0.625rem',
  },
  emptyState: {
    textAlign: 'center',
    padding: '4rem 2rem',
    color: 'white',
    background: 'rgba(255, 255, 255, 0.15)',
    backdropFilter: 'blur(10px)',
    borderRadius: '20px',
    border: '2px dashed rgba(255, 255, 255, 0.3)',
  },
};